### ISSUE TITLE
Navbar and other Href attributes don't load the other Html sites properly.

### ISSUE THREAD

**Issue by TheBlackVoid** [TheBlackVoid/Portfolio#1]
Title sais it all.

**Comment by zeb-stephen-downs** [comment]
@TheBlackVoid Clarify, please? The links seem to be working fine for me.

**Comment by TheBlackVoid** [comment]
Just fixed it! There was some inconsistency with lowercase and uppercase

**Comment by zeb-stephen-downs** [comment]
Yeah, I noticed that. Generally, it's best to keep file names lowercase and use dashes instead of spaces for cross-platform, avoiding issues, etc. I also noticed you have some inline CSS; you should probably move all that into CSS stylesheet files and link to them. Good luck!

**Comment by TheBlackVoid** [comment]
Thank you for the kind words! This is my first website EVER to be published! So I have little experience, in fact, I started doing HTML seriously about 2 and a half weeks ago!

Thank you!
ps: I'll look into that.
