### ISSUE TITLE
home button going to wrong site

### ISSUE THREAD

**Issue by TheBlackVoid** [TheBlackVoid/Portfolio#2]
If you go to my [website](https://theblackvoid.github.io/Portfolio/) and try to press the "Home" button you will get redirected to a domain that doesn't exist! 

I was just interested in the domain tab in the settings and realized I couldn't do a custom one and reset it. Now it's trying to go to that domain. 

Thanks!

**Comment by zeb-stephen-downs** [comment]
@TheBlackVoid Seems to be working fine for me... Try holding down Shift + F5 until the page reloads, then click Home; this will ignore the cache.

**Comment by TheBlackVoid** [comment]
Still doesn't work! 
Example: https://gyazo.com/6e28406add76a9ef7b8ac985788530a2
Thanks for the quick help!

**Comment by zeb-stephen-downs** [comment]
@TheBlackVoid That's really odd because when you mouse over it, it's showing the correct link. Have you tried it in another browser or profile without any extensions/add-ons?
