### ISSUE TITLE
Animation bug!

### ISSUE THREAD

**Issue by TheBlackVoid** [TheBlackVoid/Portfolio#3]
On my website on the first page when you first enter it there is an animation that has the code: `@keyframes snow{
  from {margin-top:500px;}
  to{margin:-5px;}` But there is a verry odd thing where it somehow seems to add a padding during the animation. How do I fix this?

example: https://gyazo.com/5496c25184b797c6d8411c2eca2b2273

**Comment by ddevereauxx** [comment]
I believe what you're seeing is actually a result of your final declaration of the margin not padding. Try `@keyframes snow{ from {margin-top:500px;} to{margin-top:-5px;}` instead.

**Comment by TheBlackVoid** [comment]
Thank you! this worked perfectly!
